### PR TITLE
prettify (wow!)

### PR DESCRIPTION
**Pull request by jonsterling**
@david-christiansen look at this trick I learned! Before merging, I'll want to make this a non-default option in the mode, though.

### CODE REVIEW

**Comment by david-christiansen** [comment]
What a kludge! Are you sure you want this in the mode, as opposed to the mode's documentation?

**Comment by david-christiansen** [comment]
Also, `(foo . (bar bz))` means the same thing as `(foo bar baz)`.

**Comment by jonsterling** [comment]
> What a kludge! Are you sure you want this in the mode, as opposed to the mode's documentation?

Ha, fair! I think this qualifies as the sort of weird hack that the total two people who would want this can just add to their own configurations...

**Comment by david-christiansen** [comment]
:-)

**Pull request closed without merging**
