### PR TITLE
Change license to assign copyright to the RedPRL Development Team

### PR DESCRIPTION
**Pull request by jonsterling**
I wonder if this makes the most sense? I think it's permissible to do this, but just wanted to check that everyone was OK with it.

### CODE REVIEW

**Comment by jonsterling** [comment]
Thank you for the feedback!

**Comment by favonia** [comment]
I wonder what could be an issue for using the RedPRL team as the copyright owner.... we probably need a lawyer here. In any case, a very formal approach is to ask everyone to sign some copyright assignment like this https://cla.github.com/. I'm using the review mechanism as a lightweight, less formal alternative. @jonsterling Maybe you can request reviews from past significant contributors.

**Comment by jonsterling** [comment]
@favonia Whenever you're happy with this PR feel free to merge!

**Comment by favonia** [comment]
@jonsterling My only worry is the past significant contributors---who else should we ask, if any? Otherwise I'm done.

**Comment by jonsterling** [comment]
@favonia Well, since nobody else was assigned copyright, I guess it's not technically a problem... But thinking back the main other significant contributor was @wilcoxjay, who provided the first implementation of the typing rules for Kan operations.

**Comment by favonia** [comment]
Thanks. Well, this is not an urgent issue and we have plenty of time.

**Comment by wilcoxjay** [comment]
I'm happy with this.

**Comment by favonia** [comment]
Thank you all for your responses.

**Pull request merged**
