### PR TITLE
RedPPRL is not fresh anymore. Sorry!

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by cangiuli** [comment]
Wait, fix the vim mode!

**Comment by favonia** [comment]
@cangiuli Sorry I forgot Vim is also very old.

**Comment by favonia** [comment]
Wait, you beat me in git-committing.

**Comment by cangiuli** [comment]
Taste it!

**Comment by cangiuli** [comment]
(Feel free to merge.)

**Pull request merged**
