### PR TITLE
add a safe version of eval

### PR DESCRIPTION
**Pull request by jonsterling**
#112 

@Cangiuli This should hopefully address what we discussed this evening.

### CODE REVIEW

**Comment by jonsterling** [comment]
And nicely enough, this check doesn't break any of our examples.

**Comment by cangiuli** [comment]
If the original term passes the check, but what it steps to fails the check, does the error cause the entire tactic to be rewound?

**Comment by jonsterling** [comment]
@cangiuli Under the current behavior, what should happen is that the tactic steps until it cannot step any further (under the check). So, if `M1 :-> M2 :-> M3 :-> M4`, and `M1,M2,M3` are good but `M4` has a free dimension variable in the head operator, this rule will step `M1` to `M3`.

**Comment by jonsterling** [comment]
@cangiuli I suppose it is a little trickier than that in fact—because this is a machine, this may result in computation occurring in the principle argument to some non-canonical operator—and this non-canonical operator may have free dimension variables. I wonder if that makes a difference?

Maybe it is necessary to have a more sophisticated version of this.

**Comment by cangiuli** [comment]
Right, you want to check the principal argument's head constructor. Otherwise you conclude `S1-elim(loop[x]; 5, _.true)` is in bool even though `<0/x>` of it computes to `5`.

**Comment by jonsterling** [comment]
@cangiuli OK, that much makes sense, and I think at least that behavior is implemented here...

The case that I was worried about in my last comment is, I think, probably not possible given that we always start from a "freshly loaded" machine state, and we check this condition prior to taking each step.

**Comment by jonsterling** [comment]
By the way, this is one of the nice things about using a machine as opposed to SOS or (worse!) natural semantics—because there are no recursive calls in the implementation of the transition system (as would happen in SOS), we can interleave this check with evaluation easily & safely. Otherwise, we would have to implement the whole thing over again I think...

**Pull request merged**
