### PR TITLE
start adding json stuff

### PR DESCRIPTION
**Pull request by jonsterling**
- [x] atomic sorts
- [x] atom operators
- [x] level operators
- [x] ctt operators
- [x] tactic operators
- [x] record operators
- [x] top-level operators
- [x] LCS sorts
- [x] LCS operators
- [x] rig up JSON encoder for redprl abts
- [x] encode signatures
- [x] decode signatures

### CODE REVIEW

**Comment by jonsterling** [comment]
Hmm, I can't figure out what's going wrong with the mlb file...

**Comment by jonsterling** [comment]
Ah, I think I see what is happening. I seem to have misunderstood how MLton resolves paths. Here's what I expected to happen:

> With path map `LIBS lib`, any MLB file resolves `$(LIB)` to the `lib` folder at the root directory of the project, or, the directory from which `mlton` was run.

The above is consistent with how SML/NJ's CM appears to work. Instead, what appears to happen is the following:

> With path map `LIBS lib`, any MLB file resolves `$(LIB)` to the `lib` folder at the level of the current `mlb` file.

I can see how this behavior makes sense, but it seems to make much more difficult the case where an application can specify the location of its libraries dependencies. Under this behavior, an absolute path would seem to be required, but this absolute path must be determined once for every working copy of the repository. Do I understand this right, @MatthewFluet?

We can solve this locally by using `pwd` in the build script, though.

**Comment by MatthewFluet** [comment]
@jonsterling Yes, MLton's MLB path variables are somewhat different from SML/NJ's CM path anchors.  Within an MLB file, when processing a file reference, any MLB path variables are (recursively) expanded and the resulting path is interpreted as relative to the immediate containing MLB file (or interpreted as absolute, if the path has a leading `/`).  In fact, MLB path variables need not correspond to full paths at all and, therefore, aren't changed when processing nested MLB files.

From what I see with RedPRL, with all(?) of the dependencies pulled in as submodules under the (root) `lib` directory, then using an absolute path would work, but so would simply using `../lib` or `../../lib` as necessary.  I acknowledge that the later does inhibit some kinds of moving sources without also updating various MLB files.

**Comment by jonsterling** [comment]
@MatthewFluet thanks for clarifying! I've ended up using the absolute path thing, and determining the proper one in the build script.

The `../lib` thing works well enough internally to RedPRL, but the problem is that many of our dependencies themselves have dependencies which are shared, so in that case, the absolute path thing is needed. One thing that might be ideal would be to sufficiently functorize our libraries such that there is only one level of dependencies; this might make things a bit frustrating to use, though, so we haven't done it.

**Comment by jonsterling** [comment]
I think I'll merge this now, and then I can begin to use this machinery in another pull request.

The point of this work, btw, was to provide a machine-readable serialization format for RedPRL signatures which is not sensitive to changes in concrete notation; I want to use this to cache proofs, kind of like Agda does with the `.agdai` files.

**Comment by MatthewFluet** [comment]
@jonsterling Ah, yes, now I see that you want `./lib/json-lib` to use the shared `./lib/cmlib` rather than its "local" sub-module `./lib/json-lib/lib/cmlib`.  The absolute path thing is probably the best approach.

**Pull request merged**
