### PR TITLE
All for the Omega1(S1).

### PR DESCRIPTION
**Pull request by favonia**
Getting closer to #383.

### CODE REVIEW

**Comment by favonia** [comment]
@jonsterling Try the following for a seemingly infinite loop. (You need `S1UnivCover` in the current development.) I wonder what is the best way to fix this? If I inline `Loop`, then the seemingly infinite loop would go away, but in a more complicated situation I would run into another seemingly infinite loop. Therefore I think it is important to figure out the actual cause. Perhaps we need something like #438 to do breadth-first search?

```
Thm Loop : [
  (path [_] S1 base base)
] by [
  abs i => `(loop i)
].

Thm S1LoopToInt : [
  (-> (path [_] S1 base base) int)
] by [
  lam l => `(coe 0~>1 [x] ($ S1UnivCover (@ l x)) 0);
    claim eq : [(= S1 (@ l 1) base)] by [auto];
    refine coe/eq; auto;
    [ fresh x -> rewrite eq at type; [`($ S1UnivCover x)]; auto
    , fresh x -> rewrite eq at left; [`($ S1UnivCover x)]; auto
    ]
].

Thm S1LoopConcat : [
  (->
   (path [_] S1 base base)
   (path [_] S1 base base)
   (path [_] S1 base base))
] by [
  lam p q => abs x => `(hcom 0~>1 S1 (@ p x) [x=0 [_] base] [x=1 [y] (@ q y)])
].

Thm S1LoopInv : [
  (->
   (path [_] S1 base base)
   (path [_] S1 base base))
] by [
  lam p => abs x => `(hcom 0~>1 S1 base [x=0 [y] (@ p y)] [x=1 [_] base])
].

Thm IntToS1Loop : [
  (-> int (path [_] S1 base base))
] by [
  lam i => fresh n ih -> elim i;
    [ abs _ => `base
    , `($ S1LoopConcat Loop ih)
    , `($ S1LoopInv Loop)
    , `($ S1LoopConcat ($ S1LoopInv Loop) ih)
    ]
].

Thm Test0 : [
  (= int ($ S1LoopToInt ($ IntToS1Loop 1)) 1)
] by [
  auto; ?
].
```

**Comment by jonsterling** [comment]
Interesting... It's a bit concerning...

The auto tactic is so complex right now it feels like we have little control (or expectation) of what it will do. I wonder if what you suggested in #438 will help mitigate the issue; it seems a good idea regardless...

**Comment by favonia** [comment]
@jonsterling Sorry I have been offline for the last week. What would be the recommended way to make progress? I wish we could finish this before the tutorial. I suppose adding some debugging functionality in the current LCF would help a lot.

**Comment by jonsterling** [comment]
@favonia I'm now able to start digging into RedPRL again; would you like me to try and debug this?

**Comment by favonia** [comment]
@jonsterling Yes, please. In particular, I think some support from the LCF library would help a lot.

We could merge this PR first, btw. Or I can start the internalization of EQ judgments.

**Comment by jonsterling** [comment]
@favonia Some kind of debugging support in the LCF library would be awesome. What did you have in mind? Maybe I can implement it...

And you can feel free to merge this PR whenever you want.

**Comment by favonia** [comment]
I want the ability to (1) put "RedPrlLog" into action and (2) ability to inspect the derivation tree, or at least know the location of a subgoal in it. How about https://github.com/RedPRL/sml-dependent-lcf/issues/40 and then turn each currently useless logging statement into some appending operation to the meta information? I want to know how exactly each goal is generated.

**Comment by jonsterling** [comment]
@favonia Maybe I can implement a version of the LCF monad that instruments each proof state with a tree, so that you can see where everything came from.

**Comment by favonia** [comment]
The above strange loop is more-or-less because when the type of `hcom` is a neutral term (containing an unfold symbol `Loop` in this case), `HCom.TubeL` will be tried first because `ComputeBefore` is useless. And then all the uncontrolled trouble...

**Pull request merged**
