### PR TITLE
propagate exit codes in scripts (close #578)

### LINKED ISSUE #578: travis testing succeeds even if some examples are failing
Like https://travis-ci.org/RedPRL/sml-redprl/jobs/337619065. A false positive. @cangiuli @jonsterling

### PR DESCRIPTION
**Pull request by jonsterling**
To resolve #578

### CODE REVIEW

**Comment by cangiuli** [comment]
I thought I tested this! Maybe I was only testing `run-tests.sh`? But your fix works for me.

Sorry for "fixing" the builds!

**Comment by favonia** [comment]
I see! So the issue is the failure of propagating the error code in the pipeline...

**Comment by jonsterling** [comment]
@favonia Does this look OK now?

**Comment by favonia** [comment]
Personally I would declare `set -o pipeline` upfront, but this is also fine. There are several things I wonder why a default bash does not take as the default setup...

**Pull request merged**
