### PR TITLE
Add integers, stage 0.

### PR DESCRIPTION
**Pull request by favonia**
Fulfilling #56.

### CODE REVIEW

**Comment by favonia** [comment]
@jonsterling I think we can try to merge this first without the ability to prove anything interesting. So the dependency is that interesting operators must wait for the new machine, and the renaming of wool will be in git-conflict with integers. I suggest this PR -> machine -> wool -> more on integers or other stuff.

**Comment by jonsterling** [comment]
@favonia I think this looks like a reasonable start.

Question: is there any reason to make numerals a parameter sort? It might be simpler to define the operator like this:

```
data mono_operator = ... | NUMBER of int
```

**Comment by favonia** [comment]
@jonsterling Do you want to reason about integers abstractly? Then you probably want a number sort. See the attached testing cases. Otherwise yeah we do not need the `ParamTerm`.

**Comment by favonia** [comment]
@jonsterling I was talking about this:
```
Thm Abstract{i:num} : [
  (number i) in int
] by [
  auto
].
```

**Comment by jonsterling** [comment]
Ah, I see. Well, I'm fine with having it be the way you wrote it.

**Pull request merged**
