### PR TITLE
Strict univalence [WIP]

### PR DESCRIPTION
**Pull request by jonsterling**
#189 

- [x] `ia{r}`
- [ ] `iain{r}`
- [ ] `iaout{r}`

### CODE REVIEW

**Comment by jonsterling** [comment]
I ended up experimenting with some changes to the frontend/interaction model in this branch. Just going to go with it, rather than try to integrate them into master beforehand. Suffice it to say that RedPRL will soon be a LOT more fun to use.

**Comment by jonsterling** [comment]
My plan is to get this branch up to date, remove the nascent isovalence changes for now (we can add it back later), and get this merged.

The main changes in this PR actually have nothing to do with isovalence, and are about the frontend.

/cc @favonia

**Comment by favonia** [comment]
@jonsterling It seems the unmerged code actually already went into RedPRL (except `IA`). Is that correct?

**Comment by jonsterling** [comment]
Probably I cherry picked the commits I needed at one point.  Hard to remember

**Comment by favonia** [comment]
My real question was whether I can delete this branch and claim the branch `univalence`. I picked a different name in the end, but I think we can still delete this branch if it's useless.

**Comment by jonsterling** [comment]
yes, feel free to delete and replace with your branch

**Pull request closed without merging**
