### PR TITLE
Alternative notation for composition.

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by jonsterling** [comment]
this looks awesome!

**Comment by favonia** [comment]
@jonsterling I assume you approved.

**Comment by jonsterling** [comment]
Yes, I definitely approve :) From my phone, I don't know how to "officially" approve

**Comment by cangiuli** [comment]
Aren't we calling it `fcom` instead of `fhcom`? (I know this isn't specific to this pull request.)

**Comment by favonia** [comment]
@cangiuli I believe it will be `fcom`, but at least I do not want to touch it while changing other parts...

**Pull request merged**
