### PR TITLE
Final Forcing Framework

### PR DESCRIPTION
**Pull request by favonia**
Related to #262 #230 #221.

### CODE REVIEW

**Comment by jonsterling** [comment]
@favonia The structure you've started writing here looks interesting; I guess it has forcing in one place only, which (based on what you have said) sounds necessary. Do you think that this will work?

**Comment by favonia** [comment]
@jonsterling I think it will work, but not as well as I hope it will do.

**Comment by favonia** [comment]
@jonsterling By the way, do you mind if I create macros like `\EE` for `\mathcal{E}`?

**Comment by jonsterling** [comment]
@favonia That's fine

**Comment by favonia** [comment]
@jonsterling I'd like to do the merging in the end if you feel this pull request is okay.

**Comment by jonsterling** [comment]
Great! I think I understand what you've done, but would you mind explaining how it works?

And am I right that the only instance of forcing is when you compose the two F substitutions?

**Comment by jonsterling** [comment]
yes, whenever you are ready, feel free to merge

**Comment by favonia** [comment]
@jonsterling There are also forcing in the form of `M[...]`.

**Pull request merged**
