### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by jonsterling** [comment]
Jesus Christ, now SML/NJ build is broken for some reason. :(

**Comment by jonsterling** [comment]
And it builds fine on my machine 😦

**Comment by jonsterling** [comment]
OK, this branch fails locally on a fresh clone. good.

**Comment by favonia** [comment]
The current `test-sml.sh` will still run the tests (against the last successful build) even if the building fails. Not sure how to fix this in a robust way. Is this what causes the problems here? The travis build is always trustworthy because the directory `bin` is newly created.

**Comment by jonsterling** [comment]
@favonia What went wrong is that I am an idiot 😆  I screwed up the `.cm` file of one of the dependencies, now fixed. It's really hard to find the errors in the SML/NJ output!

**Pull request merged**
