### PR TITLE
Unstable beta rules

### PR DESCRIPTION
**Pull request by ecavallo**
Beta rules for the unstable reductions of `s1-rec` (`loop`) and `pushout-rec` (`glue`). The rules as they are specified here are justified by the lemma I mentioned in #495.

### CODE REVIEW

**Comment by favonia** [comment]
I wonder if we can just have one single tactic to do unstable computation for well-typed term? The machine already supports unstable computation.

**Comment by cangiuli** [comment]
Related question: do we currently have a tactic that says if a term is closed, it is equal to its unstable value? This will be handy for complicated calculations involving univalence.

**Comment by ecavallo** [comment]
@favonia Yes, definitely. But the machine needs to be modified in the following way:
> given an open term M, the machine should return a term N and a list E of equations such that M\psi |->* N\psi for any \psi which does not make any of the equations in E true.
To prove M = P in C, if the machine produces (N,E) on input M, then the generated subgoals are M = P in C [\xi] for each \xi in E. (In particular, if the reduction is stable, then there are no subgoals.)

(Types aren't closed under arbitrary unstable computation, if that is what you were suggesting.)

**Comment by jonsterling** [comment]
Nice work.

**Comment by jonsterling** [comment]
> Related question: do we currently have a tactic that says if a term is closed, it is equal to its unstable value? This will be handy for complicated calculations involving univalence.

We don't yet have this, but it sounds sensible.

And @ecavallo's idea of changing the machine to generate this list sounds interesting too; I'd like to understand it a bit better on paper, but it sounds promising.

**Comment by ecavallo** [comment]
[Here](http://www.cs.cmu.edu/~ecavallo/garbage/typed-reduction.pdf) is some paper.

**Comment by jonsterling** [comment]
@ecavallo I am sorry that I lost track of this! Thanks for adding it...

I want to coordinate it's merge with @favonia. And re: your idea for enhancing the machine, I think that also sounds cool! Sometime we should figure out how to carry it out.

**Comment by jonsterling** [comment]
I'm going to close this and momentarily reopen another one

**Pull request closed without merging**
