### PR TITLE
[WIP] Interactive mode

### PR DESCRIPTION
**Pull request by ak3n**
- [x] Simple JSON REPL
- [x] Support code in chunks

### CODE REVIEW

**Comment by jonsterling** [comment]
Cool! Let me know when you want me to have a look at this.

**Comment by freebroccolo** [comment]
You might find [flow-json-schema](https://github.com/freebroccolo/flow-json-schema/blob/master/sig/index.js) useful when it comes to specifying some of the JSON bits or for validation purposes. I already use this in the RedPRL language mode for typing the parts related to [mode configuration](https://github.com/freebroccolo/atom-language-redprl/blob/master/lib/config.js#L4-L6).

Here's an [example schema](https://github.com/freebroccolo/emacs-input-methods/blob/master/schema/schema.yaml) which I use to specify the [JSON data](https://github.com/freebroccolo/emacs-input-methods-assets/tree/master/assets/gz) for input methods in [atom-input-assist](https://github.com/freebroccolo/atom-input-assist). I also have a somewhat poorly written [validator](https://github.com/freebroccolo/emacs-input-methods/blob/master/script/validate) that uses this schema.

**Comment by ak3n** [comment]
@jonsterling it will take some time!

@freebroccolo Thanks! 

Please, check out #95.

**Comment by ak3n** [comment]
Okay, somebody should try to use it. You need to:

- Install https://github.com/RedPRL/redprl-ipython-kernel
- Install jupyter (pip3 install jupyter)
- Build this branch
- Run jupyter-notebook

or after installation of jupyter:

- Install Hydrogen for Atom (requires zeromq)

**Comment by jonsterling** [comment]
This sounds really cool! Sorry I haven't had a chance to check it out yet, I've been hard at work on a new paper…

Is there anything I can do to help with the Travis problem?

**Comment by ak3n** [comment]
I think you should update [sml-json](https://github.com/RedPRL/sml-json).

**Comment by jonsterling** [comment]
@ak3n Ah, ok! I'll do it today hopefully, or, if I don't make it, I've given you administrator's access.

**Comment by jonsterling** [comment]
@ak3n Ok, I've updated `sml-json`, so Travis should work again; how would you feel about pushing directly to https://github.com/RedPRL/sml-json in the future? One of the things I'd like to do as much as possible is maintain our dependencies within the RedPRL organization on GitHub so that we can ensure continued buildability over the years.

**Comment by ak3n** [comment]
@jonsterling ofc, no problems.

**Comment by jonsterling** [comment]
@ak3n Can you revert 7adacccb6e875b266b5ba4e6661c4290ea483823? This is an old version of the `sml-typed-abts` library.

**Comment by jonsterling** [comment]
@ak3n Sorry, I got confused with the git shas. I'm going to fix this and get it ready to be merged...

**Comment by jonsterling** [comment]
I've got this merged in via PR #96. Thanks @ak3n, and sorry for the long wait! I've finished moving to Pittsburgh, so I will be much more responsive in the future.

**Comment by ak3n** [comment]
@jonsterling Congratulations! It's not a perfect solution, but it works.

**Pull request closed without merging**
