### PR TITLE
More aggressively skip useless subgoals of the *COM family.

### PR DESCRIPTION
**Pull request by favonia**
Use `Restriction.make*IfDifferent` in more settings.

### CODE REVIEW

**Comment by favonia** [comment]
I am thinking that maybe in the future a rule can take an argument indicating whether even the number of auxiliary goals should be the same under arbitrary substitution. It's relatively easy to revert the optimization.

**Comment by jonsterling** [comment]
> I am thinking that maybe in the future a rule can take an argument indicating whether even the number of auxiliary goals should be the same under arbitrary substitutions.

That's an interesting idea, but I don't think it's what I want to do... It continues to make things more complicated. I would like the rules to be very simple and not do sophisticated things; it would be better to produce *all* the subgoals, and then discharge these automatically using tactics. There is some performance overhead, but I have a feeling it won't be prohibitive.

But I'm not trying to make that change now; we can look at it later, after the important stuff is done.

**Comment by favonia** [comment]
Alright, but such a tactic will benefit from a slightly more powerful LF I think---the ability to search across different subgoals and find redundancy. For example, if there are two identical subgoals, we only have to prove one of them.

**Comment by jonsterling** [comment]
> For example, if there are two identical subgoals, we only have to prove one of them.

That's a great idea! I think we can support something like that if we think carefully. The only question will be whether it is in practice actually less expensive to do this searching than it would be to prove the thing `n` times (if you have 300 subgoals, which happens easily, it might be very expensive to hunt for duplicates).

**Comment by favonia** [comment]
Is it easy to support searching within the subgoals generated by a particular rule?

**Comment by jonsterling** [comment]
@favonia Subgoals don't carry any information about what rule they came from, so that's not easy. Ultimately, I think it is best (as a general principle, not necessarily in each particular case) if automation tactics only look at the shape of goals, and not try to do fancy things depending on what rule was used, etc.

**Comment by favonia** [comment]
I meant a "rule modifier" in a tactic that takes the subgoals of a rule before merging the telescopes into one.

**Comment by jonsterling** [comment]
@favonia Ah! Do you mean just like "apply this rule/tactic, and then let me do something with the subgoals generated by it"?

If so, then yes, that's what "multitactics" do. We only have a few multitactics at this time: one applies another tactic to all the subgoals, another applies a list of tactics pointwise to the subgoals, etc.

**Comment by favonia** [comment]
Yes, and I think we can have a very sophisticated multitactic to mimic most of the `IfDifferent` and `IfLess` optimizations. It would probably be more expensive, though, as you predicted. Also, some invariants (like if a function type `(-> A B)` is in universe `i` then `A` is also in universe `i`) are probably not provable without another rule.

**Comment by jonsterling** [comment]
My thought is that at some point (not now, I don't want to distract from the important stuff), we can try turning off the optimizations. If performance is still not horrible, there's no need to immediately work on such a multitactic; but if performance becomes really bad, we could think about the design of such a multitactic.

**Comment by favonia** [comment]
As a record I think this PR reduces ~10% of the goals according to the experiments on `connection.prl`.

**Comment by jonsterling** [comment]
That's quite impressive! Feel free to merge, btw---the convo about rule optimizations in general is separate from the day-to-day issues, on which I follow your judgment completely.

**Comment by jonsterling** [comment]
Agreed.

**Pull request merged**
