### PR TITLE
Try the cap and tube rules on both sides.

### LINKED ISSUE #209: Make connections work!
It will be great if we can type check this with only `auto`? (Currently RedPRL is quite slow and looks buggy on this, not to mention proving it.)

```
Thm Connection(#A) : [
  a/type : #A type >>
     (a : #A)
  -> (b : #A)
  -> (p : paths({_}.#A; a; b))
  -> paths({i}.(paths({_}.#A; a; p@i)); <_>a; p)
] by [
  {
  lam a. lam b. lam p.
    <i> <j> 'hcom{i=0,i=1,j=0,j=1;0~>1}(#A; ,a;
     {k}.hcom{k=0,k=1;1~>j}(#A; hcom{k=0,k=1;1~>0}(#A; ,p @ k; {_}.,a; {j}.,p @ j); {_}.,a; {_}.,a);
     {k}.hcom{k=0,k=1;1~>j}(#A; ,p @ k; {_}.,a; {j}.,p @ j);
     {k}.hcom{k=0,k=1;1~>i}(#A; hcom{k=0,k=1;1~>0}(#A; ,p @ k; {_}.,a; {i}.,p @ i); {_}.,a; {_}.,a);
     {k}.hcom{k=0,k=1;1~>i}(#A; ,p @ k; {_}.,a; {j}.,p @ j))
  };
].
```

### PR DESCRIPTION
**Pull request by favonia**
Together with #228, this will fix #209.

### CODE REVIEW

**Comment by favonia** [comment]
I deleted the example so that we can cleanly merge this first while fixing the coe example in #228.

**Comment by jonsterling** [comment]
@favonia Sorry for the delay; I'll look at this now.

**Comment by favonia** [comment]
@jonsterling I can refactor the code even further---what we want (as a ugly hack) is a wrapper to flip the top equational judgment. In fact, the EQ rule should try both sides too, but so far it is sufficient to prove the current examples.

**Comment by jonsterling** [comment]
@favonia If it works, let's leave it the way it is for now, since I think the code is reasonable looking.

**Pull request merged**
