### PR TITLE
Sequel to FFFF.

### PR DESCRIPTION
**Pull request by favonia**
@jonsterling Is this what you are asking for?

By the way, there are design issues such as whether we should just keep a list in the end. I think that is a little bit too far unless you would force everything immediately.

### CODE REVIEW

**Comment by favonia** [comment]
Wait, let me fix some stupid bug...

**Comment by jonsterling** [comment]
Hi @favonia, thanks for this!

Would it be possible to add a case in the last section for an arbitrary operator `\theta`? That is,  how forcing works on a term `\theta({x...}[a...]. M ....)`.

**Comment by jonsterling** [comment]
(probably it's straightforward, but it would be helpful to see)

**Comment by favonia** [comment]
@jonsterling I am not sure how to typeset it. Should I use the syntax for meta variables?

**Comment by jonsterling** [comment]
@favonia Yeah, I think so; an operator is (schematically) an operator head `\vartheta` together with a list of binders, which you could write `\vec{x};\vec{a}.M` (as in the 2nd-order substitutions).

The one thing to be cautious about is that operator heads vary over dimensions, so you will have to apply a dimension substitution to an operator head, as in `\vartheta\psi`.

**Comment by favonia** [comment]
@jonsterling So, there are pros and cons for either keeping a list of "final substitution" in the end or collapsing them early. Do you have some intuition about how to figure out which is more efficient?

**Comment by jonsterling** [comment]
@favonia It's hard for me to tell at this point...

**Comment by favonia** [comment]
@jonsterling Anyways, does the note make more sense now? I might still miss something somewhere.

**Comment by favonia** [comment]
@jonsterling Just added some words to give some intuition about the final list.

**Comment by jonsterling** [comment]
@favonia I'll try to read through it again tonight (my brain is a little fried right now). thanks for writing this up!!

**Pull request merged**
