### PR TITLE
Lightweight copyright assignment.

### LINKED ISSUE #626: Set up CONTRIBUTING and solve (most) legal issues at once
@jonsterling I am trying to strike a balance between legal perfection and zero bureaucracy. How about a CONTRIBUTING file mentioning the copyright assignment? This means:

- [ ] Create CONTRIBUTING to make clear about copyright assignment and technical guildlines
- [ ] Enable https://help.github.com/articles/setting-guidelines-for-repository-contributors/

### PR DESCRIPTION
**Pull request by favonia**
Close #626, hopefully.

### CODE REVIEW

**Comment by favonia** [comment]
Please feel free to update the text if it reads too bureaucratic.

**Comment by jonsterling** [comment]
I'm fine with this! I guess others should also comment.

**Comment by favonia** [comment]
I rewrote it again because "not solely owned by you" was so confusing.

**Comment by favonia** [comment]
I was expecting that https://help.github.com/articles/setting-guidelines-for-repository-contributors/ would work, but it does not. Any idea why?

**Pull request merged**
