### PR TITLE
integrate new version of dependent-lcf with backtracking support

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by jonsterling** [comment]
Some issues:

1. Errors are reported twice
2. Source positions are not appropriately attached to errors anymore (to fix, will require a change to the LCF library)

**Comment by jonsterling** [comment]
I think this seems to work properly now!

**Comment by jonsterling** [comment]
@favonia I'd like to get this merged soon to avoid introducing conflicts with whatever you are doing next... Do you think it's ready to merge, or do you have any suggestions?

**Comment by favonia** [comment]
I don't think I would have time to review this by tomorrow, and I don't want to delay important changes, so yes.

**Comment by jonsterling** [comment]
@favonia OK!

**Pull request merged**
