### PR TITLE
Universes, stage 0.

### PR DESCRIPTION
**Pull request by favonia**
Only when #319 is also done the universes can be considered done.

### CODE REVIEW

**Comment by favonia** [comment]
@jonsterling Ah your comment is squashed out...

**Comment by favonia** [comment]
@jonsterling What is your favorite *concrete* notation for "a Kan universe at level (max i j)" in our S#-expression style?

**Comment by jonsterling** [comment]
Maybe (U kan (lmax i j))?  But I don't care too much, do it as you like :)

**Comment by favonia** [comment]
Actually I do not know what to do with `(lmax i j)` in S#-expressions. They are not expressions.

The outer parentheses must be `{}`.

**Comment by jonsterling** [comment]
There's not a hard rule; sometimes the param vs term distinction is an implementation detail. no need to get the notation perfect, since we can easily change it.

**Comment by favonia** [comment]
Before reverting the mode of the universe level argument and figuring out the right way to have multiple outputs, we can still type-check everything by explicitly providing the universe levels. And that's what I'll do now.

**Comment by jonsterling** [comment]
ok, agreed!

**Comment by favonia** [comment]
Because there are no elim rules for universe levels, I am switching to inf-nary representations. Examples:
```
{lmax {labove a 3} {labove b} c {labove {lmax c d} 1} 2}
{lvl 100}
```

**Comment by jonsterling** [comment]
@favonia This looks very interesting! Your ideas for universe levels are a lot more advanced than anything I have considered, and it seems like we will be able to do a lot of cool stuff with it! Nice.

**Comment by favonia** [comment]
I would like to merge this PR first because it also refactors other parts such as the `RedPrlError` module.

**Comment by favonia** [comment]
Oh, wait, I would like to remove `STRATIFIED` as well.

**Comment by favonia** [comment]
@jonsterling Now it's really done (for this PR).

**Pull request merged**
