### PR TITLE
[experimental, do not merge] integrate updated lcf lib

### PR DESCRIPTION
**Pull request by jonsterling**

### CODE REVIEW

**Comment by jonsterling** [comment]
(The reason I haven't merged this is that it's a bit slower than the old one. I want to optimize it a bit first.)

**Comment by jonsterling** [comment]
I should be using some kind of state monad here.

**Comment by favonia** [comment]
Is this subsumed by #523?

**Comment by jonsterling** [comment]
@favonia No; this is some experiments I was doing on a new design, but it's nowhere near ready to merge.

**Comment by cangiuli** [comment]
Please don't delete this branch.

**Pull request closed without merging**
