### PR TITLE
Add motives.

### LINKED ISSUE #559: Consider adding motives to the terms for `if` and `nat-rec`
I would like to propose or open for discussion the matter of adding motives to `nat-rec`, etc. Right now, it is not possible to automatically check membership for terms defined using `nat-rec`, nor is it possible to synthesize their types. This results in frustratingly requiring the user to intervene and write down a type in their tactic script, somewhere far away from where the `nat-rec` was defined.

I want to advance the Thought, **"It's OK If Hard Things Are Hard, But Easy Things Should Be Easy"**. A corollary to this Thought is that we should be able to typecheck routine uses of `nat-rec` that arise from proof-refinement.

One disadvantage of doing this is that term sizes will increase.

### PR DESCRIPTION
**Pull request by favonia**
This will resolve #559. The example `example/semi-simplicial.prl` is not fixed yet, though.

### CODE REVIEW

**Comment by favonia** [comment]
Great! Now it fails properly, as it should. :smile:

**Comment by favonia** [comment]
@jonsterling One option is to comment out the failing part until we can do them almost automatically. There are instances of #534.

**Comment by jonsterling** [comment]
@favonia Yes; I would endorse commenting it out. The proof is very nearly automatic once we deal with the `synth` stuff.

**Comment by jonsterling** [comment]
@favonia (Check out my old exploratory branch which implemented both motives and the improved synthesis, https://github.com/RedPRL/sml-redprl/blob/improve-synth-improved/example/semi-simplicial.prl. I make no guarantees about correctness though)

**Comment by favonia** [comment]
@jonsterling Hmm I thought I saw some commuting conversions which I doubt can be solved by synth, but the output's so messy and I could not really tell.

**Comment by jonsterling** [comment]
Yes, it's really hard to tell... My feeling is that these are the kinds of proofs which we should not be doing: if we really have to reason with output that is this gnarly, we should just change the way that RedPRL works; the synth stuff helps in one respect, and also your idea for improved unfolding of recursive definitions would probably also help a lot.

**Comment by jonsterling** [comment]
It may also be that in my experimental branch, I made some other changes to `auto` that made this work better. I just can't remember, because I was kind of delirious when I wrote it.

**Pull request merged**
