### PR TITLE
Improve vim mode.

### PR DESCRIPTION
**Pull request by cangiuli**
I'm going to improve the vim mode in a number of ways, including better syntax highlighting. Now is a good time to make any feature requests (beyond #575 and #589).

### CODE REVIEW

**Comment by favonia** [comment]
1. Sometimes when the error points to a line that needs scrolling, Vim fails to redraw the screen properly... how should I help debug?
2. Is it possible to make each message foldable?
3. Could we have some command as fancy as "check theorems and definitions to the current one as if `Quit.` was inserted after the current block"?
4. After implementing #589, some way to manually kill it.

**Comment by favonia** [comment]
5. I am not sure, but maybe it is cool to highlight the numerals...

**Comment by cangiuli** [comment]
Thanks! Regarding (1), @jonsterling has also reported this, although I'm not sure I've run into it myself. I can try adding a `redraw` and see if it helps.

**Comment by favonia** [comment]
An alternative to #589: shows that RedPRL has done the checking.

**Comment by cangiuli** [comment]
@favonia Is this the behavior you wanted with respect to foldable messages? (Check a RedPRL buffer and then type `zM` in the messages buffer.)

**Comment by favonia** [comment]
@cangiuli I was thinking about folding _error_ messages when some are them are very long, but what you did is definitely great!

**Comment by cangiuli** [comment]
@favonia Try out `:call CheckBufferToCursor()`, which checks the buffer only up to the line that the cursor is on. You asked for a similar function but to the end of the "current block," but I'm not sure how to detect that. Do you have any suggestions? Is the current behavior useful?

**Comment by cangiuli** [comment]
@favonia I think I can also fold error messages, but I actually don't know how to produce very long error messages in RedPRL! Can you give me a hint about how? :)

**Comment by favonia** [comment]
I remember it's something of wrong sort of something. You can probably get one by screwing up one of the rewrites in the semi-simplicial types file.

**Pull request merged**
